In [11]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [12]:
fraud_df = pd.read_csv('../data/processed/cleaned_fraud_data.csv',parse_dates=["signup_time", "purchase_time"])
credit_df = pd.read_csv('../data/processed/cleaned_credit_data.csv')

# Rescaling numerical data

In [13]:
num_cols = ['purchase_value', 'time_delta', 'device_sharing_count','tx_count_1h_device']
scaler = StandardScaler()

fraud_df[num_cols] = scaler.fit_transform(fraud_df[num_cols])
fraud_df.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class,device_sharing_count,country,time_delta,purchase_hour,purchase_day,tx_count_1h_user,tx_count_24h_user,tx_count_1h_device
0,2,2015-01-11 03:47:13,2015-02-21 10:03:37,0.931338,FGBQNDNBETFJJ,SEO,Chrome,F,25,880217484,0,-0.261514,United States,-0.437279,10,5,1.0,1.0,-0.184457
1,4,2015-06-02 16:40:57,2015-09-26 21:32:16,0.221836,MKFUIVOHLJBYN,Direct,Safari,F,38,2785906106,0,-0.261514,Switzerland,1.633857,21,5,1.0,1.0,-0.184457
2,8,2015-05-28 07:53:06,2015-08-13 11:53:07,0.549298,SCQGQALXBUQZJ,SEO,Chrome,M,25,356056736,0,-0.261514,United States,0.555032,11,3,1.0,1.0,-0.184457
3,9,2015-05-16 15:58:32,2015-05-20 23:06:42,1.367955,IEZOHXPZBIRTE,SEO,FireFox,M,21,759104706,0,-0.261514,Unknown,-1.458852,23,2,1.0,1.0,-0.184457
4,12,2015-01-10 06:25:12,2015-03-04 20:56:37,-0.105627,MSNWCFEHKTIOY,Ads,Safari,M,19,2985180352,0,-0.261514,Mexico,-0.096136,20,2,1.0,1.0,0.550182

In [14]:
from sklearn.preprocessing import RobustScaler, StandardScaler

amount_scaler = RobustScaler()
credit_df['scaled_amount'] = amount_scaler.fit_transform(credit_df[['Amount']])

time_scaler = StandardScaler()
credit_df['scaled_time'] = time_scaler.fit_transform(credit_df[['Time']])

credit_df = credit_df.drop(columns=['Amount', 'Time'])
credit_df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V22,V23,V24,V25,V26,V27,V28,Class,scaled_amount,scaled_time
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0,1.783274,-1.996583
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,0,-0.269825,-1.996583
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,0,4.983721,-1.996562
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0,1.418291,-1.996562
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,0,0.670579,-1.996541

# One-hot encoding categorical features

In [15]:
cat_cols = ['source', 'browser', 'sex']
fraud_df = pd.get_dummies(fraud_df, columns=cat_cols, drop_first=True)
fraud_df.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,age,ip_address,class,device_sharing_count,country,...,tx_count_1h_user,tx_count_24h_user,tx_count_1h_device,source_Direct,source_SEO,browser_FireFox,browser_IE,browser_Opera,browser_Safari,sex_M
0,2,2015-01-11 03:47:13,2015-02-21 10:03:37,0.931338,FGBQNDNBETFJJ,25,880217484,0,-0.261514,United States,...,1.0,1.0,-0.184457,False,True,False,False,False,False,False
1,4,2015-06-02 16:40:57,2015-09-26 21:32:16,0.221836,MKFUIVOHLJBYN,38,2785906106,0,-0.261514,Switzerland,...,1.0,1.0,-0.184457,True,False,False,False,False,True,False
2,8,2015-05-28 07:53:06,2015-08-13 11:53:07,0.549298,SCQGQALXBUQZJ,25,356056736,0,-0.261514,United States,...,1.0,1.0,-0.184457,False,True,False,False,False,False,True
3,9,2015-05-16 15:58:32,2015-05-20 23:06:42,1.367955,IEZOHXPZBIRTE,21,759104706,0,-0.261514,Unknown,...,1.0,1.0,-0.184457,False,True,True,False,False,False,True
4,12,2015-01-10 06:25:12,2015-03-04 20:56:37,-0.105627,MSNWCFEHKTIOY,19,2985180352,0,-0.261514,Mexico,...,1.0,1.0,0.550182,False,False,False,False,False,True,True

# Handling Class Imbalance - SMOTE

In [16]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

In [20]:
X = fraud_df.drop(columns=['class', 'signup_time', 'purchase_time', 'user_id', 'device_id', 'ip_address'])
y = fraud_df['class']

X = pd.get_dummies(X, drop_first=True)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


print("BEFORE SMOTE (Training Set):")
print(y_train.value_counts())

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("\nAFTER SMOTE (Training Set):")
print(y_train_resampled.value_counts())

BEFORE SMOTE (Training Set):
class
0    109568
1     11321
Name: count, dtype: int64

AFTER SMOTE (Training Set):
class
0    109568
1    109568
Name: count, dtype: int64

In [21]:
X_credit = credit_df.drop(columns=['Class'])
y_credit = credit_df['Class']

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_credit, y_credit, test_size=0.2, random_state=42, stratify=y_credit
)
print("BEFORE SMOTE (Training Set):")
print(y_train.value_counts())

smote = SMOTE(random_state=42)
X_train_resampled_c, y_train_resampled_c = smote.fit_resample(X_train_c, y_train_c)

print("\nAFTER SMOTE (Training Set):")
print(y_train_resampled.value_counts())

BEFORE SMOTE (Training Set):
class
0    109568
1     11321
Name: count, dtype: int64

AFTER SMOTE (Training Set):
class
0    109568
1    109568
Name: count, dtype: int64

In [23]:
X_train_resampled.to_csv('../data/processed/fraud_X_train_smote.csv', index=False)
y_train_resampled.to_csv('../data/processed/fraud_y_train_smote.csv', index=False)
X_test.to_csv('../data/processed/fraud_X_test.csv', index=False)
y_test.to_csv('../data/processed/fraud_y_test.csv', index=False)

X_train_resampled_c.to_csv('../data/processed/credit_X_train_smote.csv', index=False)
y_train_resampled_c.to_csv('../data/processed/credit_y_train_smote.csv', index=False)
X_test_c.to_csv('../data/processed/credit_X_test.csv', index=False)
y_test_c.to_csv('../data/processed/credit_y_test.csv', index=False)